### ISSUE TITLE
Feature Request: Differentiate Pulls/Issues in Output

### ISSUE THREAD

**Issue by ghost** [maxpowa/sopel-github#129]
Right now the bot says something like:

> [GitHub] helix-editor/helix - A post-modern modal text editor. | 83.6% Rust 15.1% Scheme 0.6% Handlebars 0.7% Other | Last Push: 2023-08-19 @ 05:00CDT | Stargazers: 24179 | Watchers: 163 | Forks: 1740 | Network: 1740 | Open Issues: 1111

Ideally it would say (at this exact moment), something like:

> [...] | Open Issues: 806 | Open PRs: 305

or

> [...] | Open Issues: 806 | Open Pulls: 305

---

If the GitHub API makes this impossible...well...*curses M$FT*.

**Comment by dgw** [comment]
I'm having a lot of trouble navigating the sample responses in their tiny scrollable panes on my phone… The repository info feature fetches the [`/repos/:owner/:name` API resource](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository), so if you (or future-me) can find a relevant field therein, it'll be easy.

Alternate approach? Probably would have to issue at least [one additional API request](https://api.github.com/search/issues?q=repo:sopel-irc/sopel%20is:pr%20state:open) to fetch the PR count (`total_results`) and then subtract the open PR count from the total open issues.
